export const CATEGORIES_ACTION_TYPES = {
  SET_CATEGORES_MAP: "category/SET_CATEGORES_MAP",
  FETCH_CATEGORIES_START: "category/FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCEEDED: "category/FETCH_CATEGORIES_SUCCEEDED",
  FETCH_CATEGORIES_FAILED: "category/FETCH_CATEGORIES_FAILED",
};
